server:
  port: 8080
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-server