eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8086
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    api-a:
      path: /standard-consumer/**
      serviceId: standard-consumer
    api-b:
      path: /admin-consumer/**
      serviceId: admin-consumer


